// Simple email service without OAuth requirements
export interface EmailConfig {
  from: string;
  to: string[];
  subject: string;
  body: string;
  attachments?: Array<{
    filename: string;
    content: Blob;
  }>;
}

export class EmailService {
  // Option 1: Mailto link (client-side)
  static sendViaMailto(config: EmailConfig): void {
    const subject = encodeURIComponent(config.subject);
    const body = encodeURIComponent(config.body);
    const to = config.to.join(',');
    
    window.open(`mailto:${to}?subject=${subject}&body=${body}`, '_blank');
  }

  // Option 2: Copy email content to clipboard
  static copyToClipboard(config: EmailConfig): void {
    const emailContent = `
To: ${config.to.join(', ')}
Subject: ${config.subject}

${config.body}
    `.trim();
    
    navigator.clipboard.writeText(emailContent).then(() => {
      alert('Email content copied to clipboard! Paste it in your email client.');
    });
  }

  // Option 3: Generate HTML email template
  static generateEmailTemplate(invoiceData: any): string {
    return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice: ${invoiceData.invoiceNumber}</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { border-bottom: 2px solid #0F1B2D; padding-bottom: 20px; margin-bottom: 20px; }
        .invoice-details { background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 20px; }
        .total { background: #10B981; color: white; padding: 15px; border-radius: 8px; font-size: 18px; font-weight: bold; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Invoice ${invoiceData.invoiceNumber}</h1>
            <p>Issue Date: ${invoiceData.issueDate}</p>
            <p>Due Date: ${invoiceData.dueDate}</p>
        </div>
        
        <div class="invoice-details">
            <h3>Bill To:</h3>
            <p><strong>${invoiceData.clientName}</strong></p>
            <p>${invoiceData.clientEmail}</p>
        </div>

        <h3>Items:</h3>
        <table style="width: 100%; border-collapse: collapse;">
            <thead>
                <tr style="background: #0F1B2D; color: white;">
                    <th style="padding: 10px; text-align: left;">Description</th>
                    <th style="padding: 10px; text-align: right;">Quantity</th>
                    <th style="padding: 10px; text-align: right;">Rate</th>
                    <th style="padding: 10px; text-align: right;">Amount</th>
                </tr>
            </thead>
            <tbody>
                ${invoiceData.items.map((item: any) => `
                <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">${item.description}</td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd; text-align: right;">${item.quantity}</td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd; text-align: right;">$${item.rate.toFixed(2)}</td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd; text-align: right;">$${item.amount.toFixed(2)}</td>
                </tr>
                `).join('')}
            </tbody>
        </table>

        <div class="total">
            Total Amount: ${invoiceData.currency} ${invoiceData.total.toFixed(2)}
        </div>

        ${invoiceData.signatureData ? `
        <div style="margin-top: 30px; text-align: center;">
            <img src="${invoiceData.signatureData}" alt="Signature" style="max-height: 60px;" />
            <p style="font-size: 12px; color: #666; margin-top: 10px;">Authorized Signature</p>
        </div>
        ` : ''}

        <div class="footer">
            <p>This invoice was generated by Solopreneur OS</p>
            <p>Thank you for your business!</p>
        </div>
    </div>
</body>
</html>
    `.trim();
  }

  // Option 4: Export to email file
  static exportAsEmailFile(config: EmailConfig): void {
    const emailContent = this.generateEmailTemplate({
      invoiceNumber: 'INV-' + Date.now(),
      clientName: config.to[0],
      clientEmail: config.to[0],
      subject: config.subject,
      body: config.body,
      issueDate: new Date().toLocaleDateString(),
      dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString(),
      items: [],
      total: 0,
      currency: 'USD',
      signatureData: ''
    });

    const blob = new Blob([emailContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `invoice-email.html`;
    a.click();
    URL.revokeObjectURL(url);
  }
}
